### ISSUE TITLE
Add an option to supply PASV_ADDRESS

### ISSUE THREAD

**Issue by ricardogsilva** [million12/docker-vsftpd#6]
In order to be able to use `passive` mode when the container is inside a docker swarm (or any other situation where there is a proxy) it is necessary to use vsftpd's `PASV_ADDRESS` configuration setting.

This option could be exposed in a similar way as the others.

I have a working implementation of this feature in my fork of this repo and will supply a PR shortly.

**Comment by pozgo** [comment]
Fixed with PR [#7](https://github.com/million12/docker-vsftpd/pull/7)
